plugins {
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'org.example.cours.cours5.ampoule.version2.client.App'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.vavr:vavr:0.10.5'
    testImplementation 'junit:junit:4.13.2'
}