plugins {
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'org.example.cours.cours5.ampoule.version2.client.App'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.vavr:vavr:0.10.5'
}